// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhwUaeK6ETvr5LpJG0HSW0mmWX9JjMHIk',
    appId: '1:765407091224:web:36e0a96d5772af2d9d816d',
    messagingSenderId: '765407091224',
    projectId: 'winzaap-3b4b9',
    authDomain: 'winzaap-3b4b9.firebaseapp.com',
    storageBucket: 'winzaap-3b4b9.firebasestorage.app',
    measurementId: 'G-KLHN044NZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTxH6nlg8kYEzOb1RuF_LcoAKAhot1sXw',
    appId: '1:765407091224:android:0740415c4f29b64d9d816d',
    messagingSenderId: '765407091224',
    projectId: 'winzaap-3b4b9',
    storageBucket: 'winzaap-3b4b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxB1jGVEBCwxlYZNXWRS8eS5rhEuYx2jo',
    appId: '1:765407091224:ios:3d60e0d0e1086e9d9d816d',
    messagingSenderId: '765407091224',
    projectId: 'winzaap-3b4b9',
    storageBucket: 'winzaap-3b4b9.firebasestorage.app',
    iosBundleId: 'com.himanshu.winzaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxB1jGVEBCwxlYZNXWRS8eS5rhEuYx2jo',
    appId: '1:765407091224:ios:34389ed34ad394a49d816d',
    messagingSenderId: '765407091224',
    projectId: 'winzaap-3b4b9',
    storageBucket: 'winzaap-3b4b9.firebasestorage.app',
    iosBundleId: 'com.example.winzaap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhwUaeK6ETvr5LpJG0HSW0mmWX9JjMHIk',
    appId: '1:765407091224:web:6c55a27579be604a9d816d',
    messagingSenderId: '765407091224',
    projectId: 'winzaap-3b4b9',
    authDomain: 'winzaap-3b4b9.firebaseapp.com',
    storageBucket: 'winzaap-3b4b9.firebasestorage.app',
    measurementId: 'G-HMY1J6T530',
  );
}
